# Generated by Django 5.2.5 on 2025-09-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Adjustment'), ('sale_cancellation', 'Sale Cancellation'), ('sale', 'Sale'), ('return', 'Return')], max_length=20),
        ),
    ]
