#!/usr/bin/env python3
"""
backend/build_protected.py
Automated build script for creating protected Django distribution (Windows optimized)
Optimized for GitHub Actions CI/CD
"""

import os
import sys
import shutil
import subprocess
import glob
from pathlib import Path

class DjangoProtectedBuilder:
    def __init__(self, project_root="."):
        self.project_root = Path(project_root).resolve()
        self.build_dir = self.project_root / "build"
        self.dist_dir = self.project_root / "dist_protected"
        
    def clean(self):
        """Clean previous builds"""
        print("🧹 Cleaning previous builds...")
        
        # Directories to clean
        dirs_to_clean = [
            self.build_dir,
            self.dist_dir,
        ]
        
        for dir_path in dirs_to_clean:
            if dir_path.exists():
                shutil.rmtree(dir_path, ignore_errors=True)
                print(f"   Removed: {dir_path}")
        
        # Remove egg-info directories
        for egg_info in self.project_root.glob("*.egg-info"):
            shutil.rmtree(egg_info, ignore_errors=True)
            print(f"   Removed: {egg_info}")
        
        # Remove .c files generated by Cython
        for c_file in self.project_root.rglob("*.c"):
            if "build" not in str(c_file):
                try:
                    c_file.unlink()
                except:
                    pass
        
        print("✅ Cleanup completed\n")
    
    def build_extensions(self):
        """Build Cython extensions"""
        print("🔨 Building Cython extensions...")
        
        result = subprocess.run(
            [sys.executable, "setup.py", "build_ext", "--inplace"],
            capture_output=True,
            text=True,
            cwd=self.project_root
        )
        
        if result.returncode != 0:
            print("❌ Build failed:")
            print(result.stdout)
            print(result.stderr)
            return False
        
        # Show some output
        if result.stdout:
            for line in result.stdout.split('\n'):
                if 'compiling' in line.lower() or 'creating' in line.lower():
                    print(f"   {line}")
        
        print("✅ Cython compilation successful\n")
        return True
    
    def create_dist_structure(self):
        """Create distribution directory structure"""
        print("📁 Creating distribution structure...")
        self.dist_dir.mkdir(exist_ok=True)
        print(f"   Created: {self.dist_dir}\n")
    
    def copy_compiled_extensions(self):
        """Copy .pyd files to distribution"""
        print("📦 Copying compiled extensions...")
        
        # Find all .pyd files (Windows) and .so files (if any)
        extensions = list(self.project_root.glob("**/*.pyd")) + \
                    list(self.project_root.glob("**/*.so"))
        
        count = 0
        for ext_file in extensions:
            # Skip if in build directory
            if "build" in str(ext_file) or "dist_protected" in str(ext_file):
                continue
            
            try:
                rel_path = ext_file.relative_to(self.project_root)
                dest_path = self.dist_dir / rel_path
                dest_path.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(ext_file, dest_path)
                count += 1
            except Exception as e:
                print(f"   Warning: Could not copy {ext_file}: {e}")
        
        print(f"   ✓ Copied {count} compiled extensions\n")
    
    def copy_essential_files(self):
        """Copy files that cannot be compiled"""
        print("📄 Copying essential files...")
        
        # Single files to copy
        essential_files = [
            "manage.py",
            "run_app.py",
            "requirements.txt",
            "README.md",
            ".env.example",
            "Procfile",
            "runtime.txt",
        ]
        
        for filename in essential_files:
            src = self.project_root / filename
            if src.exists():
                try:
                    shutil.copy2(src, self.dist_dir / filename)
                    print(f"   ✓ {filename}")
                except Exception as e:
                    print(f"   Warning: Could not copy {filename}: {e}")
        
        print()
    
    def copy_directories(self):
        """Copy directories that shouldn't be compiled"""
        print("📁 Copying resource directories...")
        
        # Directories to copy entirely
        dirs_to_copy = [
            "static",
            "staticfiles",
            "media",
            "templates",
            "locale",
            "fixtures",
        ]
        
        for dir_name in dirs_to_copy:
            src_dir = self.project_root / dir_name
            if src_dir.exists():
                dest_dir = self.dist_dir / dir_name
                if dest_dir.exists():
                    shutil.rmtree(dest_dir, ignore_errors=True)
                try:
                    shutil.copytree(src_dir, dest_dir)
                    print(f"   ✓ {dir_name}/")
                except Exception as e:
                    print(f"   Warning: Could not copy {dir_name}: {e}")
        
        print()
    
    def copy_migrations(self):
        """Copy migration files (must remain as .py)"""
        print("🔄 Copying migration files...")
        
        migration_files = list(self.project_root.glob("**/migrations/*.py"))
        count = 0
        
        for migration_file in migration_files:
            if "build" in str(migration_file) or "dist_protected" in str(migration_file):
                continue
            
            try:
                rel_path = migration_file.relative_to(self.project_root)
                dest_path = self.dist_dir / rel_path
                dest_path.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(migration_file, dest_path)
                count += 1
            except Exception as e:
                print(f"   Warning: Could not copy {migration_file}: {e}")
        
        print(f"   ✓ Copied {count} migration files\n")
    
    def copy_init_files(self):
        """Copy __init__.py files (needed for Python packages)"""
        print("📝 Copying __init__.py files...")
        
        init_files = list(self.project_root.glob("**/__init__.py"))
        count = 0
        
        for init_file in init_files:
            # Skip certain directories
            skip_dirs = ["build", "dist_protected", "__pycache__", ".git", "venv", "env", ".venv"]
            if any(skip_dir in str(init_file) for skip_dir in skip_dirs):
                continue
            
            try:
                rel_path = init_file.relative_to(self.project_root)
                dest_path = self.dist_dir / rel_path
                dest_path.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(init_file, dest_path)
                count += 1
            except Exception as e:
                print(f"   Warning: Could not copy {init_file}: {e}")
        
        print(f"   ✓ Copied {count} __init__.py files\n")
    
    def copy_special_files(self):
        """Copy files that need special handling"""
        print("⚙️  Copying configuration files...")
        
        # Files that should remain as .py
        special_patterns = [
            "**/wsgi.py",
            "**/asgi.py",
            "**/apps.py",
            "**/admin.py",
        ]
        
        count = 0
        for pattern in special_patterns:
            for file in self.project_root.glob(pattern):
                if "build" in str(file) or "dist_protected" in str(file):
                    continue
                
                try:
                    rel_path = file.relative_to(self.project_root)
                    dest_path = self.dist_dir / rel_path
                    dest_path.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(file, dest_path)
                    count += 1
                except Exception as e:
                    print(f"   Warning: Could not copy {file}: {e}")
        
        print(f"   ✓ Copied {count} configuration files\n")
    
    def create_deployment_docs(self):
        """Create deployment documentation"""
        print("📝 Creating deployment documentation...")
        
        readme_content = """# Protected Django Application

## Deployment Guide (Windows)

### Prerequisites
- Python 3.12 (same version used to build)
- Windows OS
- All dependencies from requirements.txt

### Quick Start

1. **Run the deployment script:**
```cmd
deploy.bat
```

2. **Configure environment:**
```cmd
copy .env.example .env
REM Edit .env with your settings
```

3. **Run the application:**
```cmd
REM Development
run_server.bat

REM Production
run_production.bat
```

### Manual Installation

1. **Create virtual environment:**
```cmd
python -m venv venv
venv\\Scripts\\activate
```

2. **Install dependencies:**
```cmd
pip install -r requirements.txt
```

3. **Run migrations:**
```cmd
python manage.py migrate
```

4. **Collect static files:**
```cmd
python manage.py collectstatic --noinput
```

5. **Create superuser (optional):**
```cmd
python manage.py createsuperuser
```

6. **Run server:**
```cmd
REM Development
python manage.py runserver

REM Production with Waitress
waitress-serve --port=8000 --threads=4 ims.wsgi:application
```

## Important Notes

- This is a **protected build** with compiled Cython extensions (.pyd files)
- Source code is compiled and not human-readable
- Extensions are platform-specific (Windows x64)
- Python version must match exactly (3.12)

## System Requirements

- OS: Windows 10/11 (x64)
- Python: 3.12.x
- RAM: 2GB minimum
- Disk: 500MB minimum

## Production Deployment

For production, use Waitress:
```cmd
pip install waitress
waitress-serve --port=8000 --threads=4 ims.wsgi:application
```

Or use IIS with wfastcgi:
```cmd
pip install wfastcgi
wfastcgi-enable
```

## Troubleshooting

### Import Errors
- Ensure Python version matches: `python --version`
- Check all .pyd files are present in the directories

### Module Not Found
- Install all dependencies: `pip install -r requirements.txt`
- Verify virtual environment is activated

### Static Files Not Loading
- Run: `python manage.py collectstatic --noinput`
- Check STATIC_ROOT in settings

### Database Errors
- Check database configuration in .env
- Run migrations: `python manage.py migrate`

## Support

For issues, contact your development team.
"""
        
        (self.dist_dir / "DEPLOYMENT.md").write_text(readme_content, encoding='utf-8')
        print("   ✓ DEPLOYMENT.md\n")
    
    def create_env_example(self):
        """Create example environment file"""
        if not (self.dist_dir / ".env.example").exists():
            env_content = """# Django Settings
DEBUG=False
SECRET_KEY=your-secret-key-here-change-this-in-production
ALLOWED_HOSTS=localhost,127.0.0.1

# Database
DATABASE_URL=sqlite:///db.sqlite3
# For PostgreSQL: postgresql://user:password@localhost:5432/dbname
# For MySQL: mysql://user:password@localhost:3306/dbname

# Security
CSRF_COOKIE_SECURE=True
SESSION_COOKIE_SECURE=True

# Static/Media
STATIC_ROOT=staticfiles/
MEDIA_ROOT=media/

# Email (optional)
EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
"""
            (self.dist_dir / ".env.example").write_text(env_content, encoding='utf-8')
            print("   ✓ Created .env.example\n")
    
    def generate_build_info(self):
        """Generate build information file"""
        print("ℹ️  Generating build information...")
        
        import datetime
        import platform
        
        build_info = f"""Build Information
==================

Build Date: {datetime.datetime.now().isoformat()}
Platform: {platform.system()} {platform.machine()}
Python Version: {sys.version}
Build Type: Cython Protected (.pyd)

This is a protected build with compiled Cython extensions.
Source code has been compiled to native Windows extensions (.pyd files).

Files protected: All Python source files except:
- __init__.py
- manage.py
- run_app.py
- wsgi.py/asgi.py
- Migration files
- Admin.py files
- Apps.py files

For deployment instructions, see DEPLOYMENT.md
"""
        
        (self.dist_dir / "BUILD_INFO.txt").write_text(build_info, encoding='utf-8')
        print("   ✓ BUILD_INFO.txt\n")
    
    def verify_build(self):
        """Verify the build output"""
        print("✅ Verifying build...")
        
        # Check for .pyd files
        pyd_files = list(self.dist_dir.glob("**/*.pyd"))
        
        if not pyd_files:
            print("   ⚠️  Warning: No compiled extensions found!")
            return False
        
        print(f"   ✓ Found {len(pyd_files)} compiled extensions (.pyd)")
        
        # Check for essential files
        essential = ["manage.py", "requirements.txt"]
        for filename in essential:
            if (self.dist_dir / filename).exists():
                print(f"   ✓ {filename} present")
            else:
                print(f"   ⚠️  {filename} missing")