# Generated by Django 5.2.5 on 2025-09-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='business_type',
            field=models.CharField(blank=True, choices=[('retail', 'Retail Store'), ('restaurant', 'Restaurant'), ('service', 'Service Provider'), ('wholesale', 'Wholesale'), ('other', 'Other')], max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_logos/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='Default tax rate %', max_digits=5),
        ),
    ]
