# Generated by Django 5.2.5 on 2025-09-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_business_type_vendor_currency_vendor_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='about',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
