# Generated by Django 5.2.5 on 2025-09-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='about',
            new_name='tagline',
        ),
        migrations.AddField(
            model_name='vendor',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
