# Generated by Django 5.2.5 on 2025-09-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_rename_about_vendor_tagline_vendor_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='tax_number',
            new_name='gstin',
        ),
    ]
