# Generated by Django 5.2.5 on 2025-09-05 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_user_commission_rate_user_hire_date_and_more'),
        ('vendors', '0002_vendor_business_type_vendor_currency_vendor_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='vendors.vendor'),
        ),
    ]
