# Generated by Django 5.2.5 on 2025-08-22 15:54

import django.core.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='product_name',
            field=models.CharField(default='test name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product_sku',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['payment_status'], name='sales_sale_payment_f41ab8_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'product'], name='sales_salei_sale_id_17278e_idx'),
        ),
    ]
