# Generated by Django 5.2.5 on 2025-09-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_saleitem_product_name_saleitem_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='credit_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
